Add support for App Store Connect API Key (#88)
* Make password optional.

(cherry picked from commit 4b00836c4b1a49acc8d3998260dcbef13f82811b)

* Fix deliver password env.

(cherry picked from commit a3824e7dbbf688997beffdd495b65f524a8ad33b)

* Add support for App Store Connect API Key

* Separate go-tests workflow for local testing.

* Fix Go static check issues.

* Add envs for API Key testing

* Turn on password input.

* Change input validation to require a password for apple id authentication

* Add APIKey documentation

* Skip notes where appropriate

* Add test for api key authentication

* Fix increment-build-number workflow

* Fix 860980d

* Add titles to test workflows

* Fix c025d42

* Enable test-api-key-auth

* Exclude In-app purchases from precheck when using API Key authentication

* Fix build number calculation

Co-authored-by: Krisztián Gödrei <krisztian.godrei@bitrise.io>

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -10,12 +10,11 @@ app:
   - INFO_PLIST_PATH: ./Bitrise-iTunesConnectBetaTest/Bitrise-iTunesConnectBetaTest/Info.plist
 
   # define these in your .bitrise.secrets.yml
-  - BITRISE_BUILD_NUMBER: $BITRISE_BUILD_NUMBER
-  - BITRISE_BUILD_VERSION_OFFSET: $BITRISE_BUILD_VERSION_OFFSET
-
   - ITUNES_CONNECT_USER: $ITUNES_CONNECT_USER
   - ITUNES_CONNECT_PASSWORD: $ITUNES_CONNECT_PASSWORD
   - ITUNES_CONNECT_APP_SPECIFIC_PASSWORD: $ITUNES_CONNECT_APP_SPECIFIC_PASSWORD
+  - ITUNES_CONNECT_API_KEY_PATH: $ITUNES_CONNECT_API_KEY_PATH
+  - ITUNES_CONNECT_API_KEY_ISSUER: $ITUNES_CONNECT_API_KEY_ISSUER
   - ITUNES_CONNECT_TEAM_ID: $ITUNES_CONNECT_TEAM_ID
   - ITUNES_CONNECT_APP_ID: $ITUNES_CONNECT_APP_ID
 
@@ -25,15 +24,61 @@ workflows:
   ci:
     before_run:
     - audit-this-step
+    - go-tests
+    after_run:
+    - test
+
+  go-tests:
     steps:
     - go-list:
     - golint:
     - errcheck:
     - go-test:
-    after_run:
-    - test
 
   test:
+    before_run:
+    - test-password-auth
+    - test-api-key-auth
+
+  test-password-auth:
+    title: Test password authentication
+    before_run:
+    - prepare-test
+    steps:
+    - path::./:
+        inputs:
+        - itunescon_user: $ITUNES_CONNECT_USER
+        - password: $ITUNES_CONNECT_PASSWORD
+        - app_password: $ITUNES_CONNECT_APP_SPECIFIC_PASSWORD
+        - team_id: $ITUNES_CONNECT_TEAM_ID
+        - app_id: $ITUNES_CONNECT_APP_ID
+        - skip_screenshots: "no"
+        - skip_metadata: "yes"
+        - submit_for_review: "no"
+        - fastlane_version: "latest"
+        - verbose_log: "yes"
+
+  test-api-key-auth:
+    title: Test API Key authentication
+    before_run:
+      - prepare-test
+    steps:
+    - path::./:
+        inputs:
+          - api_key_path: $ITUNES_CONNECT_API_KEY_PATH
+          - api_issuer: $ITUNES_CONNECT_API_KEY_ISSUER
+          - team_id: $ITUNES_CONNECT_TEAM_ID
+          - app_id: $ITUNES_CONNECT_APP_ID
+          - skip_screenshots: "no"
+          - skip_metadata: "yes"
+          - submit_for_review: "no"
+          - fastlane_version: "latest"
+          - verbose_log: "yes"
+
+  prepare-test:
+    title: Prepare test
+    description: |
+      This downloads and archives an example app as an input for deliver
     steps:
     - script:
         inputs:
@@ -62,6 +107,16 @@ workflows:
         inputs:
         - generate_profiles: 'yes'
         - distribution_type: app-store
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            BITRISE_BUILD_NUMBER=$(($(gdate +%Y%m%d%H%M)-200000000000))
+            if [[ -z "${$BITRISE_BUILD_NUMBER}" ]]; then
+              echo "error: failed to calculated build number"
+              exit 1
+            fi
+            envman add --key BITRISE_BUILD_NUMBER --value "${BITRISE_BUILD_NUMBER}"
     - set-xcode-build-number:
         title: Set Build Number
         run_if: true
@@ -75,19 +130,6 @@ workflows:
         - output_dir: $BITRISE_DEPLOY_DIR
         - project_path: $BITRISE_PROJECT_PATH
         - export_method: app-store
-    - path::./:
-        title: Step Test
-        inputs:
-        - itunescon_user: $ITUNES_CONNECT_USER
-        - password: $ITUNES_CONNECT_PASSWORD
-        - app_password: $ITUNES_CONNECT_APP_SPECIFIC_PASSWORD
-        - team_id: $ITUNES_CONNECT_TEAM_ID
-        - app_id: $ITUNES_CONNECT_APP_ID
-        - skip_screenshots: "no"
-        - skip_metadata: "yes"
-        - submit_for_review: "no"
-        - fastlane_version: "latest"
-        - verbose_log: "yes"
 
   # ----------------------------------------------------------------
   # --- Utility workflows
