Add test for api key authentication

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -39,6 +39,48 @@ workflows:
     - go-test:
 
   test:
+    before_run:
+    - test-password-auth
+    #- test-api-key-auth
+
+  test-password-auth:
+    before_run:
+    - prepare-test
+    steps:
+    - path::./:
+        title: Step Test password authentication
+        inputs:
+        - itunescon_user: $ITUNES_CONNECT_USER
+        - password: $ITUNES_CONNECT_PASSWORD
+        - app_password: $ITUNES_CONNECT_APP_SPECIFIC_PASSWORD
+        - team_id: $ITUNES_CONNECT_TEAM_ID
+        - app_id: $ITUNES_CONNECT_APP_ID
+        - skip_screenshots: "no"
+        - skip_metadata: "yes"
+        - submit_for_review: "no"
+        - fastlane_version: "latest"
+        - verbose_log: "yes"
+    after_run:
+      - increment-build-number
+
+  test-api-key-auth:
+    before_run:
+      - prepare-test
+    steps:
+    - path::./:
+        title: Step Test password authentication
+        inputs:
+          - api_key_path: $ITUNES_CONNECT_API_KEY_ISSUER
+          - api_issuer: $ITUNES_CONNECT_API_KEY_ISSUER
+          - team_id: $ITUNES_CONNECT_TEAM_ID
+          - app_id: $ITUNES_CONNECT_APP_ID
+          - skip_screenshots: "no"
+          - skip_metadata: "yes"
+          - submit_for_review: "no"
+          - fastlane_version: "latest"
+          - verbose_log: "yes"
+
+  prepare-test:
     steps:
     - script:
         inputs:
@@ -80,21 +122,17 @@ workflows:
         - output_dir: $BITRISE_DEPLOY_DIR
         - project_path: $BITRISE_PROJECT_PATH
         - export_method: app-store
-    - path::./:
-        title: Step Test
+
+  increment-build-number:
+    steps:
+    - script:
         inputs:
-        - itunescon_user: $ITUNES_CONNECT_USER
-        - password: $ITUNES_CONNECT_PASSWORD
-        - app_password: $ITUNES_CONNECT_APP_SPECIFIC_PASSWORD
-        - api_key_path: $ITUNES_CONNECT_API_KEY_ISSUER
-        - api_issuer: $ITUNES_CONNECT_API_KEY_ISSUER
-        - team_id: $ITUNES_CONNECT_TEAM_ID
-        - app_id: $ITUNES_CONNECT_APP_ID
-        - skip_screenshots: "no"
-        - skip_metadata: "yes"
-        - submit_for_review: "no"
-        - fastlane_version: "latest"
-        - verbose_log: "yes"
+        - content: |-
+            #!/usr/bin/env bash
+            if [[ -z "${$BITRISE_BUILD_NUMBER}" ]]; then
+              echo "error: there is no $BITRISE_BUILD_NUMBER env var specified"
+              exit 1
+            envman --add "BITRISE_BUILD_NUMBER" --value "$((BITRISE_BUILD_NUMBER + 1))"
 
   # ----------------------------------------------------------------
   # --- Utility workflows
